name: mainpro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  http: ^1.6.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.5.4
  dio: ^5.4.1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  path_provider: ^2.1.2
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.2
  file_picker: ^10.3.8
  flutter_swiper_null_safety: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - .env
  uses-material-design: true
